### ISSUE TITLE
dependabot を廃止する

### ISSUE THREAD

**Issue by sya-ri** [gKokasai/23rd.kokasai.com#127]
@cheichey
`npm-check-updates` を使った更新にした方が良いと思いましたが、いかがでしょうか？

参考: [gKokasai/panel.kokasai.com/README.md#依存関係の更新確認](https://github.com/gKokasai/panel.kokasai.com#%E4%BE%9D%E5%AD%98%E9%96%A2%E4%BF%82%E3%81%AE%E6%9B%B4%E6%96%B0%E7%A2%BA%E8%AA%8D)

**Comment by axelaspor2** [comment]
それでいきましょう
